Updates to partial points in multiple languages, tabs added, cleaned …
codio/knowledge pull request #255
Opened 2023-10-23 18:55 UTC by jairovelasquez

…some errors

2023-10-23 18:56 UTC, jairovelasquez commented
Use this link to preview the changes: https://balancefrozen-camelsonic.codio-box.uk/build/html/instructors/authoring/assessments/partial-points.html

2023-10-24 10:17 UTC, ijobling requested changes
Readme.md file install section.. one command not working for me ? see slack

2023-10-24 13:53 UTC, ijobling approved these changes

2023-10-24 13:53 UTC, ijobling approved these changes

2023-10-24 13:54 UTC, merged